/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package editors;

import enums.ConfirmType;
import java.awt.Color;
import java.util.List;
import javax.swing.JTable;
import tools.Clase;
import tools.ConfirmMessage;
import tools.DBConnection;
import tools.PopupMessage;
import main.ViewerClaseSemanal;

/**
 *
 * @author Edu
 */
public class EditorClaseSemanal extends javax.swing.JFrame {

    private String ID;
    private String diasemana;
    private String horario;
    private String numero;
    private String cantidad;
    private String tematica;
    
    private boolean changedID = false;
    private String newID;
    private List<String[]> clasesalumnos;
    private List<String[]> tematicaclases;
    
    private String[] boxInfo;
    
    private javax.swing.DefaultComboBoxModel boxclasemodel;
    private ViewerClaseSemanal VCS;
    private javax.swing.JTable tablasemanal;
    
    /**
     * Creates new form EditorClaseSemanal
     */
    public EditorClaseSemanal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        boxdia = new javax.swing.JComboBox<>();
        jLabel11 = new javax.swing.JLabel();
        jScrollPane7 = new javax.swing.JScrollPane();
        txttematica = new javax.swing.JTextPane();
        jLabel8 = new javax.swing.JLabel();
        txthorario = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        numclase = new javax.swing.JSpinner();
        btnaplicar = new javax.swing.JButton();
        btneliminar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        boxdia.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione", "Lunes", "Martes", "Miercoles", "Jueves", "Viernes", "Sabado" }));

        jLabel11.setText("Temática");

        jScrollPane7.setViewportView(txttematica);

        jLabel8.setText("Horario: ");

        txthorario.setToolTipText("00:00");

        jLabel9.setText("Dia de la semana:");

        jLabel10.setText("N° de clase en el dia:");

        btnaplicar.setText("Aplicar cambios");
        btnaplicar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnaplicarActionPerformed(evt);
            }
        });

        btneliminar.setBackground(new java.awt.Color(255, 0, 0));
        btneliminar.setText("Eliminar clase");
        btneliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btneliminarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(58, 58, 58)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9)
                    .addComponent(jLabel8)
                    .addComponent(jLabel10)
                    .addComponent(jLabel11))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txthorario, javax.swing.GroupLayout.PREFERRED_SIZE, 246, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(numclase, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(boxdia, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 694, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(91, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btneliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 236, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34)
                .addComponent(btnaplicar, javax.swing.GroupLayout.PREFERRED_SIZE, 236, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(51, 51, 51))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(txthorario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(boxdia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(numclase, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel11)
                    .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 60, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnaplicar, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btneliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(39, 39, 39))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnaplicarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnaplicarActionPerformed
        boolean first = true;
        boolean diaCambiado = false;
        boolean horaCambiada = false;
        int newNum = Integer.parseInt(numclase.getValue().toString());
        String newDia = boxdia.getSelectedItem().toString();
        String newDiaDB = Clase.setDBValue(newDia);
        String[] doselementos = txthorario.getText().split(":");
        newID = Clase.generateClassID(boxdia.getSelectedItem().toString(), doselementos[0], doselementos[1]);
        
        //Formar String con valores cambiados
        String statement = "UPDATE `clasesemanal` SET ";
        
        if(!txthorario.getText().equals(horario)){
            statement += "`hora` = '" + txthorario.getText().toUpperCase() + "' ";
            first = false;
            horaCambiada = true;
        }
        if(!boxdia.getSelectedItem().toString().equals(Clase.setClassValue(diasemana))){
            if(!first){
                statement += ", ";
            }
            statement += "`diasemana` = '" + Clase.setDBValue(boxdia.getSelectedItem().toString()) + "' ";
            first = false;
            diaCambiado = true;
        }
        if(!numclase.getValue().toString().equals(numero)){
            
            if(!first){
                statement += ", ";
            }
            statement += "`Numero` = '" + newNum + "' ";
            first = false;
        }
        
        //Chequear si cambia el ID y borrar de clasealumnos
        if(horaCambiada || diaCambiado){
            if(!first){
                statement += ", ";
            }
            statement += "`ID` = '" + newID + "' ";
            
            List<String[]> listClase = DBConnection.getInstance().selectStatement("SELECT * FROM `clasesemanal`", 5);
            for(int i = 0; i < listClase.size(); i++){
                String[] str = listClase.get(i);
                if(newDiaDB.equals(str[1]) && txthorario.getText().equals(str[2]) && numclase.getValue().toString().equals(str[3])){
                    System.out.println("CLASE YA EXISTE - ERROR");
                    new PopupMessage("Error", Color.RED).setVisible(true);
                    return;
                }
            }
            
            String selstatement1 = "SELECT * FROM `clasesalumnos` WHERE `id_clase` = '" + ID + "'";
            clasesalumnos = DBConnection.getInstance().selectStatement(selstatement1, 3);
            String selstatement2 = "SELECT * FROM `tematicaclases` WHERE `id_clase` = '" + ID + "'";
            tematicaclases = DBConnection.getInstance().selectStatement(selstatement2, 2);
            String delstatement1 = "DELETE FROM `clasesalumnos` WHERE `id_clase` = '" + ID + "'";
            DBConnection.getInstance().modificationStatement(delstatement1);
            String delstatement2 = "DELETE FROM `tematicaclases` WHERE `id_clase` = '" + ID + "'";
            DBConnection.getInstance().modificationStatement(delstatement2);
            
            changedID = true;
        }
        statement += "WHERE `clasesemanal`.`diasemana` = '" + diasemana + "' AND `clasesemanal`.`hora` = '" + horario + "'";
        
        if(!first){
            DBConnection.getInstance().modificationStatement(statement);
        }
        
        //Volver a agregar clases a clasesalumnos y tematicaclases
        if(changedID){
            for(int i = 0; i < clasesalumnos.size(); i++){
                String[] str = clasesalumnos.get(i);
                String instatement = "INSERT INTO `clasesalumnos` VALUES ('" + str[0] + "', '" + newID + "', '" + str[2] + "')";
                DBConnection.getInstance().modificationStatement(instatement);
            }
            for(int i = 0; i < tematicaclases.size(); i++){
                String[] str = tematicaclases.get(i);
                String instatement = "INSERT INTO `tematicaclases` VALUES ('" + newID + "', '" + str[1] + "')";
                DBConnection.getInstance().modificationStatement(instatement);
            }
        }
         //VER TEMATICA -------------------------------------------------------------------------
        if(!txttematica.getText().trim().equals(tematica)){
            String statement1;
            if(txttematica.getText().trim().equals("")){
                statement1 = "UPDATE `tematicaclases` SET `tematica` = null WHERE `id_clase` = '" + newID + "'";
            }else{
                statement1 = "UPDATE `tematicaclases` SET `tematica` = '" + txttematica.getText() + "' WHERE `id_clase` = '" + newID + "'";
            }
            DBConnection.getInstance().modificationStatement(statement1);
            
            
        }
        
        //Chequear que celdas no estén ocupadas en tabla
        if(changedID){
            int newNumTableValue = newNum-1;
            try{
                while(tablasemanal.getValueAt(newNumTableValue, Integer.parseInt(newDiaDB)) != null){
                    System.out.println("Cell not null values:");
                    System.out.println("    Row: " + newNumTableValue);
                    System.out.println("    Column: " + newDiaDB);

                    String[] doselementos1 = tablasemanal.getValueAt(newNumTableValue, Integer.parseInt(newDiaDB)).toString().split(" - ");
                    List<String[]> claseToChange = DBConnection.getInstance().selectStatement("SELECT * FROM `clasesemanal` WHERE `diasemana` = '" + newDiaDB + "' AND `Hora` = '" + doselementos1[0] + "'", 5);
                    String[] str = claseToChange.get(0);
                    String diasemana1 = str[1];
                    String horavieja = str[2];
                    String num = str[3];

                    int newNumClase = Integer.parseInt(num)+1;

                    String stupdate = "UPDATE `clasesemanal` SET `Numero` = '" + newNumClase + "' WHERE `clasesemanal`.`diasemana` = '" + diasemana1 + "' AND `clasesemanal`.`hora` = '" + horavieja + "'";
                    DBConnection.getInstance().modificationStatement(stupdate);

                    newNum++;
                    newNumTableValue++;
                }
            }catch(NumberFormatException e){
                e.printStackTrace();
            }catch(IndexOutOfBoundsException e){
                System.out.println(e.getMessage());
            }
        }
        
        new PopupMessage("Clase editada con exito", Color.GREEN).setVisible(true);
        dispose();
        VCS.dispose();
    }//GEN-LAST:event_btnaplicarActionPerformed

    private void btneliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btneliminarActionPerformed
        ConfirmMessage cm = new ConfirmMessage();
        cm.setECS(this);
        cm.setVCS(VCS);
        cm.setClase(diasemana, horario);
        cm.setType(ConfirmType.E_CLASESEMANAL);
        cm.setVisible(true);
    }//GEN-LAST:event_btneliminarActionPerformed

    /**
     * @param args the command line arguments
     */
    @SuppressWarnings("Convert2Lambda")
    public static void main2(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EditorClaseSemanal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new EditorClaseSemanal().setVisible(true);
            }
        });
    }
    
    public void setBox(){
        boxclasemodel = new javax.swing.DefaultComboBoxModel<>(new String[] { "Ninguna" });
        boxdia.setModel(boxclasemodel);
        for (String boxInfo1 : boxInfo) {
            boxdia.addItem(boxInfo1);
        }
    }
    
    public void setVCS(ViewerClaseSemanal VCS){
        this.VCS = VCS;
    }
    
    public void setInfo(String[] infoClase){
        this.ID = infoClase[0];
        System.out.println("ID: " + ID);
        this.diasemana = infoClase[1];
        System.out.println("Dia Semana: " + diasemana);
        this.horario = infoClase[2];
        System.out.println("Horario: " + horario);
        this.numero = infoClase[3];
        System.out.println("Numero Clase: " + numero);
        this.cantidad = infoClase[4];
        System.out.println("Cantidad: " + cantidad);
        this.tematica = infoClase[6];
        System.out.println("Tematica: " + tematica);
        
        txthorario.setText(horario);
        int numclaseint = Integer.parseInt(numero);
        numclase.setValue(numclaseint);
        txttematica.setText(tematica);
        
        String[] infoDias = {"Lunes", "Martes", "Miercoles", "Jueves", "Viernes", "Sabado"};
        boxInfo = infoDias;
        setBox();
        String clasediasemana = Clase.setClassValue(diasemana);
        boxdia.setSelectedItem(clasediasemana);
    }
    
    public void setTabla(JTable tablasemanal) {
        this.tablasemanal = tablasemanal;
        }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> boxdia;
    private javax.swing.JButton btnaplicar;
    private javax.swing.JButton btneliminar;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JSpinner numclase;
    private javax.swing.JTextField txthorario;
    private javax.swing.JTextPane txttematica;
    // End of variables declaration//GEN-END:variables

}
