/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package proyecto;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Edu
 */
public class MainFrame extends javax.swing.JFrame {
    DefaultTableModel model1 = new DefaultTableModel();
    DefaultTableModel model2 = new DefaultTableModel();
    DefaultTableModel model3 = new DefaultTableModel();
    DefaultTableModel model4 = new DefaultTableModel();
    
    private final DBConnection dbconn = new DBConnection();
    private final Connection conn;
    private final Alumno alumno = new Alumno();
    private final Clase clase = new Clase();
    private PreparedStatement prepSt = null;
    private ResultSet rs;
    
    

    /**
     * Creates new form MainFrame
     */
    public MainFrame() {
        initComponents();
        initModelConsultaAlumno();
        initModelListaAlumno();
        initModelListaSemanal();
        initModelRegistroClases();
        
        this.tabladeresultados.setModel(model1);
        tabladeresultados.setShowGrid(true);
        this.tablaalumnos.setModel(model2);
        tablaalumnos.setShowGrid(true);
        this.tablasemanal.setModel(model3);
        String[] str = new String[0];
        model3.addRow(str);
        tablasemanal.setShowGrid(true);
        this.tablaregistro.setModel(model4);
        conn = dbconn.connection();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel4 = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTable4 = new javax.swing.JTable();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel8 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablasemanal = new javax.swing.JTable();
        btnactualizarclases = new javax.swing.JButton();
        jPanel7 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        txthorario = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        numclase = new javax.swing.JSpinner();
        boxdia = new javax.swing.JComboBox<>();
        jLabel11 = new javax.swing.JLabel();
        jScrollPane7 = new javax.swing.JScrollPane();
        txttematica = new javax.swing.JTextPane();
        btncrear = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tablaregistro = new javax.swing.JTable();
        btnactualizarregistro = new javax.swing.JButton();
        jPanel9 = new javax.swing.JPanel();
        txtid = new javax.swing.JTextField();
        txtfecha = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        boxclase = new javax.swing.JComboBox<>();
        jLabel24 = new javax.swing.JLabel();
        btnveralumnos = new javax.swing.JButton();
        btnagregaralumno1 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tablaalumnos = new javax.swing.JTable();
        btnactualizaralumnos = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtnombre = new javax.swing.JTextField();
        txtdni = new javax.swing.JTextField();
        txttelefono = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtmail = new javax.swing.JTextField();
        btnbuscar = new javax.swing.JButton();
        jScrollPane5 = new javax.swing.JScrollPane();
        tabladeresultados = new javax.swing.JTable();
        jLabel7 = new javax.swing.JLabel();
        numedad = new javax.swing.JSpinner();
        boxestado = new javax.swing.JComboBox<>();
        btnlimpiar = new javax.swing.JButton();
        boxoperador = new javax.swing.JComboBox<>();
        jPanel5 = new javax.swing.JPanel();
        txtnewalumno = new javax.swing.JTextField();
        txtnewdni = new javax.swing.JTextField();
        txtnewtelefono = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        txtfechainicio = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        btnagregaralumno = new javax.swing.JButton();
        txtnewmail = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        numnewedad = new javax.swing.JSpinner();
        jScrollPane6 = new javax.swing.JScrollPane();
        txtanotaciones = new javax.swing.JTextArea();
        btntest = new javax.swing.JButton();
        btnreset = new javax.swing.JButton();

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 711, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 456, Short.MAX_VALUE)
        );

        jTable4.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane4.setViewportView(jTable4);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        tablasemanal.setAutoCreateRowSorter(true);
        tablasemanal.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Lunes", "Martes", "Miercoles", "Jueves", "Viernes", "Sabado"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        tablasemanal.setCellSelectionEnabled(true);
        tablasemanal.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablasemanalMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tablasemanal);
        tablasemanal.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.SINGLE_INTERVAL_SELECTION);

        btnactualizarclases.setText("Actualizar");
        btnactualizarclases.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnactualizarclasesActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel8Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnactualizarclases, javax.swing.GroupLayout.PREFERRED_SIZE, 302, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 959, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 465, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnactualizarclases, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jTabbedPane1.addTab("Clases Semanales", jPanel8);

        jLabel8.setText("Horario: ");

        txthorario.setToolTipText("00:00");

        jLabel9.setText("Dia de la semana:");

        jLabel10.setText("N° de clase en el dia:");

        boxdia.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione", "Lunes", "Martes", "Miercoles", "Jueves", "Viernes", "Sabado" }));

        jLabel11.setText("Temática");

        jScrollPane7.setViewportView(txttematica);

        btncrear.setText("Crear");
        btncrear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncrearActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9)
                    .addComponent(jLabel8)
                    .addComponent(jLabel10)
                    .addComponent(jLabel11))
                .addGap(30, 30, 30)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txthorario, javax.swing.GroupLayout.PREFERRED_SIZE, 246, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(numclase, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(boxdia, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 694, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(118, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btncrear, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(90, 90, 90))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(txthorario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(boxdia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(numclase, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel11)
                    .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 79, Short.MAX_VALUE)
                .addComponent(btncrear, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23))
        );

        jTabbedPane1.addTab("Crear Clase Semanal", jPanel7);

        tablaregistro.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Fecha", "Dia de la semana", "Hora", "Alumnos", "Observaciones"
            }
        ));
        jScrollPane3.setViewportView(tablaregistro);

        btnactualizarregistro.setText("Actualizar");
        btnactualizarregistro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnactualizarregistroActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 979, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnactualizarregistro, javax.swing.GroupLayout.PREFERRED_SIZE, 302, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 476, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnactualizarregistro, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jTabbedPane1.addTab("Registro Clases", jPanel6);

        txtid.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));

        jLabel13.setText("Fecha");

        jLabel22.setText("ID");

        jLabel23.setText("Clase");

        boxclase.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Ninguna" }));

        jLabel24.setText("Alumnos");

        btnveralumnos.setText("Ver alumnos");

        btnagregaralumno1.setText("Agregar");
        btnagregaralumno1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnagregaralumno1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addGap(73, 73, 73)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addComponent(jLabel24, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnveralumnos, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel22, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(9, 9, 9)
                        .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtid, javax.swing.GroupLayout.DEFAULT_SIZE, 261, Short.MAX_VALUE)
                            .addComponent(txtfecha)))
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addComponent(jLabel23, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(boxclase, 0, 259, Short.MAX_VALUE)))
                .addContainerGap(564, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel9Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnagregaralumno1, javax.swing.GroupLayout.PREFERRED_SIZE, 348, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39))
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addGap(54, 54, 54)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel22, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtid, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtfecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel23, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(boxclase, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel24, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnveralumnos))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 236, Short.MAX_VALUE)
                .addComponent(btnagregaralumno1, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37))
        );

        jTabbedPane1.addTab("Agregar a Registro", jPanel9);

        tablaalumnos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nombre", "DNI", "Edad", "Telefono", "Mail", "Estado", "Fecha inicio", "Observaciones"
            }
        ));
        jScrollPane2.setViewportView(tablaalumnos);

        btnactualizaralumnos.setText("Actualizar");
        btnactualizaralumnos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnactualizaralumnosActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 979, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnactualizaralumnos, javax.swing.GroupLayout.PREFERRED_SIZE, 302, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jScrollPane2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnactualizaralumnos, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jTabbedPane1.addTab("Lista de Alumnos", jPanel3);

        jLabel1.setText("Nombre");

        txtnombre.setToolTipText("");
        txtnombre.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));

        jLabel3.setText("DNI");

        jLabel4.setText("Mail");

        jLabel5.setText("Teléfono");

        jLabel6.setText("Estado");

        jLabel2.setText("Edad");

        btnbuscar.setText("Buscar");
        btnbuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnbuscarActionPerformed(evt);
            }
        });

        tabladeresultados.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null}
            },
            new String [] {
                "Nombre", "DNI", "Telefono", "Mail", "Edad", "Estado"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        tabladeresultados.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        tabladeresultados.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabladeresultadosMouseClicked(evt);
            }
        });
        jScrollPane5.setViewportView(tabladeresultados);

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel7.setText("Resultados");

        numedad.setModel(new javax.swing.SpinnerNumberModel(0, null, 99, 1));

        boxestado.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione", "Activo", "Inactivo" }));

        btnlimpiar.setText("Limpiar tabla");
        btnlimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnlimpiarActionPerformed(evt);
            }
        });

        boxoperador.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Igual a", "Mayor a", "Menor a" }));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane5)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(boxestado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 206, Short.MAX_VALUE)
                                .addComponent(btnbuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 236, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(54, 54, 54)
                                .addComponent(btnlimpiar, javax.swing.GroupLayout.PREFERRED_SIZE, 236, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(boxoperador, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(28, 28, 28)
                                        .addComponent(numedad, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(txtnombre)
                                        .addComponent(txtdni)
                                        .addComponent(txttelefono, javax.swing.GroupLayout.DEFAULT_SIZE, 261, Short.MAX_VALUE))
                                    .addComponent(txtmail, javax.swing.GroupLayout.PREFERRED_SIZE, 261, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(37, 37, 37))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtnombre, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtdni, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txttelefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(boxoperador, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(numedad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(boxestado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnbuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnlimpiar, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.DEFAULT_SIZE, 208, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Consulta Alumno", jPanel1);

        txtnewalumno.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));

        jLabel12.setText("DNI");

        jLabel15.setText("Nombre");

        txtfechainicio.setToolTipText("aaaa/mm/dd");

        jLabel16.setText("Mail");

        jLabel17.setText("Fecha de inicio");

        jLabel18.setText("Teléfono");

        btnagregaralumno.setText("Agregar");
        btnagregaralumno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnagregaralumnoActionPerformed(evt);
            }
        });

        jLabel19.setText("Edad");

        jLabel20.setText("Anotaciones");

        numnewedad.setModel(new javax.swing.SpinnerNumberModel(0, null, 99, 1));

        txtanotaciones.setColumns(20);
        txtanotaciones.setRows(5);
        jScrollPane6.setViewportView(txtanotaciones);

        btntest.setText("Tests");
        btntest.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btntestActionPerformed(evt);
            }
        });

        btnreset.setText("Reset");
        btnreset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnresetActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btntest)
                    .addComponent(btnreset))
                .addGap(9, 9, 9)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jScrollPane6, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(txtfechainicio, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 261, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(txtnewalumno)
                        .addComponent(txtnewdni)
                        .addComponent(txtnewtelefono, javax.swing.GroupLayout.PREFERRED_SIZE, 261, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(txtnewmail, javax.swing.GroupLayout.PREFERRED_SIZE, 261, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(numnewedad, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 153, Short.MAX_VALUE)
                .addComponent(btnagregaralumno, javax.swing.GroupLayout.PREFERRED_SIZE, 348, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(90, 90, 90))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtnewalumno, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtnewdni, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtnewtelefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtnewmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(numnewedad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtfechainicio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane6)
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 138, Short.MAX_VALUE)
                                .addComponent(btntest)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnreset)
                                .addGap(35, 35, 35))))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnagregaralumno, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        jTabbedPane1.addTab("Crear Alumno", jPanel5);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btntestActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btntestActionPerformed
        String statement1 = "INSERT INTO `alumnos` VALUES ('PERSONA 1', '19', '1165417450', 'HERNANXDSV@GMAIL.COM', '00000001', '2021/04/21', '1', null, null, 'Ninguna')";
        String statement2 = "INSERT INTO `alumnos` VALUES ('PERSONA 2', '19', '1165417451', 'HERNANXDSV@GMAIL.COM', '00000002', '2021/04/21', '1', null, null, 'Ninguna')";
        String statement3 = "INSERT INTO `alumnos` VALUES ('PERSONA 3', '19', '1165417452', 'HERNANXDSV@GMAIL.COM', '00000003', '2021/04/21', '1', null, null, 'Ninguna')";
        String statement4 = "INSERT INTO `alumnos` VALUES ('PERSONA 4', '19', '1165417453', 'HERNANXDSV@GMAIL.COM', '00000004', '2021/04/21', '1', null, null, 'Ninguna')";
        String statement5 = "INSERT INTO `alumnos` VALUES ('PERSONA 5', '19', '1165417454', 'HERNANXDSV@GMAIL.COM', '00000005', '2021/04/21', '1', null, null, 'Ninguna')";
        String statement6 = "INSERT INTO `alumnos` VALUES ('PERSONA 6', '19', '1165417455', 'HERNANXDSV@GMAIL.COM', '00000006', '2021/04/21', '1', null, null, 'Ninguna')";
        String statement7 = "INSERT INTO `alumnos` VALUES ('PERSONA 7', '19', '1165417456', 'HERNANXDSV@GMAIL.COM', '00000007', '2021/04/21', '1', null, null, 'Ninguna')";
        String statement8 = "INSERT INTO `alumnos` VALUES ('PERSONA 8', '19', '1165417457', 'HERNANXDSV@GMAIL.COM', '00000008', '2021/04/21', '1', null, null, 'Ninguna')";
        String statement9 = "INSERT INTO `alumnos` VALUES ('PERSONA 9', '19', '1165417458', 'HERNANXDSV@GMAIL.COM', '00000009', '2021/04/21', '1', null, null, 'Ninguna')";
        try{
            prepSt = conn.prepareStatement(statement1);
            prepSt.execute();
            prepSt = conn.prepareStatement(statement2);
            prepSt.execute();
            prepSt = conn.prepareStatement(statement3);
            prepSt.execute();
            prepSt = conn.prepareStatement(statement4);
            prepSt.execute();
            prepSt = conn.prepareStatement(statement5);
            prepSt.execute();
            prepSt = conn.prepareStatement(statement6);
            prepSt.execute();
            prepSt = conn.prepareStatement(statement7);
            prepSt.execute();
            prepSt = conn.prepareStatement(statement8);
            prepSt.execute();
            prepSt = conn.prepareStatement(statement9);
            prepSt.execute();
            prepSt.close();
        }catch(SQLException e){
            e.printStackTrace();
        }
    }//GEN-LAST:event_btntestActionPerformed

    private void btnagregaralumnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnagregaralumnoActionPerformed
        try{
            prepSt = conn.prepareStatement("INSERT INTO `alumnos` VALUES (?, ?, ?, ?, ?, ?, '1', null, null, ?)");
            prepSt.setString(1, txtnewalumno.getText().toUpperCase());
            prepSt.setString(2, numnewedad.getValue().toString());
            prepSt.setString(3, txtnewtelefono.getText());
            prepSt.setString(4, txtnewmail.getText().toUpperCase());
            prepSt.setString(5, txtnewdni.getText());
            prepSt.setString(6, txtfechainicio.getText());
            prepSt.setString(7, txtanotaciones.getText());
            System.out.println(prepSt);
            prepSt.execute();
            prepSt.close();

            PopupMessage pum = new PopupMessage(3);
            pum.setVisible(true);

            txtnewalumno.setText("");
            numnewedad.setValue(0);
            txtnewtelefono.setText("");
            txtnewmail.setText("");
            txtnewdni.setText("");
            txtfechainicio.setText("");
            txtanotaciones.setText("");
        }catch(SQLException e){
            e.printStackTrace();
            System.out.println(e.getMessage());
            PopupMessage pum = new PopupMessage(0);
            pum.setVisible(true);
        }
    }//GEN-LAST:event_btnagregaralumnoActionPerformed

    private void btnlimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnlimpiarActionPerformed
        int elitotal = tabladeresultados.getRowCount();
        for(int i = elitotal-1; i>=0; i--){
            model1.removeRow(i);
        }
    }//GEN-LAST:event_btnlimpiarActionPerformed

    private void tabladeresultadosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabladeresultadosMouseClicked
        int row = tabladeresultados.getSelectedRow();
        String dni = (String)tabladeresultados.getValueAt(row, 1);
        String[] arrAlumno = new String[10];
        String statement = "SELECT * FROM `alumnos` WHERE dni = " + dni;
        System.out.println(statement);
        try {
            prepSt = conn.prepareStatement(statement);
            rs = prepSt.executeQuery();
            while(rs.next()){
                arrAlumno[0] = rs.getString("Nombre");
                arrAlumno[1] = rs.getString("DNI");
                arrAlumno[2] = rs.getString("Telefono");
                arrAlumno[3] = rs.getString("Mail");
                arrAlumno[4] = rs.getString("Edad");
                arrAlumno[5] = rs.getString("Estado");
                arrAlumno[6] = rs.getString("diaclase");
                if(arrAlumno[6] != null){
                    arrAlumno[6] = clase.setClassValue(arrAlumno[6]);
                }
                arrAlumno[7] = rs.getString("horaclase");
                arrAlumno[8] = rs.getString("FechaInicio");
                arrAlumno[9] = rs.getString("Comentarios");
                if(Integer.parseInt(arrAlumno[5]) == 0){
                    arrAlumno[5] = "Inactivo";
                }else{
                    arrAlumno[5] = "Activo";
                }
            }
            prepSt.close();
        } catch (NumberFormatException | SQLException e) {
            e.printStackTrace();
        }
        
        String stselect = "SELECT * FROM `clasesemanal`";
        String stcountrows = "SELECT COUNT(*) AS rowcount FROM `clasesemanal`";
        String rowCount;
        int intRowCount;
        String[][] arrClases = new String[0][0];
        
        try {
            prepSt = conn.prepareStatement(stcountrows);
            rs = prepSt.executeQuery();
            rs.next();
            rowCount = rs.getString("rowcount");
            intRowCount = Integer.parseInt(rowCount);
            arrClases = new String[intRowCount][3];
            String diaDB;
            
            prepSt = conn.prepareStatement(stselect);
            rs = prepSt.executeQuery();
            for(int i = 0; rs.next(); i++){
                diaDB = rs.getString("diasemana");
                arrClases[i][0] = clase.setClassValue(diaDB);
                arrClases[i][1] = rs.getString("hora");
                arrClases[i][2] = rs.getString("numeroalumnos");
            }
                    
            prepSt.close();
        } catch (SQLException e) {
            System.out.println(e.getMessage());
        }
        
        EditorAlumno EA = new EditorAlumno();
        EA.setEA(EA);
        EA.setClases(arrClases);
        EA.setInfo(arrAlumno);
        EA.setBox();
        EA.setVisible(true);

    }//GEN-LAST:event_tabladeresultadosMouseClicked

    private void btnbuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnbuscarActionPerformed
        boolean check = false;
        alumno.setNombre(txtnombre.getText());
        alumno.setDNI(txtdni.getText());
        alumno.setTelefono(txttelefono.getText());
        alumno.setMail(txtmail.getText());
        alumno.setEdad((int)numedad.getValue());
        alumno.setEstado((String)boxestado.getSelectedItem());
        try{
            String statement = "SELECT * FROM `alumnos` ";
            if(!"".equals(alumno.getNombre()) ||
                !"".equals(alumno.getDNI()) ||
                !"".equals(alumno.getTelefono()) ||
                !"".equals(alumno.getMail()) ||
                alumno.getEdad() != 0 ||
                !"Seleccione".equals(alumno.getEstado())){
                statement = statement + "WHERE ";
                if(!"".equals(alumno.getNombre())){
                    statement = statement + "`nombre` LIKE '" + alumno.getNombre() + "%' ";
                    check = true;
                }
                if(!"".equals(alumno.getDNI())){
                    if(check == true){
                        statement += "AND ";
                    }
                    statement = statement + "`DNI` LIKE '" + alumno.getDNI() + "%' ";
                    check = true;
                }
                if(!"".equals(alumno.getTelefono())){
                    if(check == true){
                        statement += "AND ";
                    }
                    statement = statement + "`Telefono` LIKE '" + alumno.getTelefono() + "%' ";
                    check = true;
                }
                if(!"".equals(alumno.getMail())){
                    if(check == true){
                        statement += "AND ";
                    }
                    statement = statement + "`Mail` LIKE '" + alumno.getMail() + "%' ";
                    check = true;
                }
                if(alumno.getEdad() != 0){
                    if(check == true){
                        statement += "AND ";
                    }
                    String operador;
                    if("Igual a".equals(boxoperador.getSelectedItem())){
                        operador = "=";
                    }else if("Mayor a".equals(boxoperador.getSelectedItem())){
                        operador = ">";
                    }else{
                        operador = "<";
                    }
                    statement = statement + "`Edad` " + operador +  " '" + alumno.getEdad() + "' ";
                    check = true;
                }
                if(!"Seleccione".equals(alumno.getEstado())){
                    if(check == true){
                        statement += "AND ";
                    }
                    if("Activo".equals(alumno.getEstado())){
                        statement = statement + "`Estado` = 1 ";
                    }else{
                        statement = statement + "`Estado` = 0 ";
                    }
                }
            }
            System.out.println(statement);
            prepSt = conn.prepareStatement(statement);
            rs = prepSt.executeQuery();
            while(rs.next()){
                String nombre = rs.getString("Nombre");
                String DNI = rs.getString("DNI");
                String telefono = rs.getString("Telefono");
                String mail = rs.getString("Mail");
                String edad = rs.getString("Edad");
                String estado = rs.getString("Estado");
                if(Integer.parseInt(estado) == 0){
                    estado = "Inactivo";
                }else{
                    estado = "Activo";
                }
                String[] resalumno = {nombre, DNI, telefono, mail, edad, estado};
                model1.addRow(resalumno);
            }
            prepSt.close();
        }
        catch(NumberFormatException | SQLException e){
            e.printStackTrace();
        }
    }//GEN-LAST:event_btnbuscarActionPerformed

    private void btnactualizaralumnosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnactualizaralumnosActionPerformed
        int elitotal = tablaalumnos.getRowCount();
        for(int i = elitotal-1; i>=0; i--){
            model2.removeRow(i);
        }
        String statement = "SELECT * FROM `alumnos`";
        try {
            System.out.println(statement);
            prepSt = conn.prepareStatement(statement);
            rs = prepSt.executeQuery();
            while(rs.next()){
                String nombre = rs.getString("Nombre");
                String DNI = rs.getString("DNI");
                String telefono = rs.getString("Telefono");
                String mail = rs.getString("Mail");
                String edad = rs.getString("Edad");
                String estado = rs.getString("Estado");
                String fechainicio = rs.getString("FechaInicio");
                String comentarios = rs.getString("Comentarios");
                if(Integer.parseInt(estado) == 0){
                    estado = "Inactivo";
                }else{
                    estado = "Activo";
                }
                String[] resalumno = {nombre, DNI, telefono, mail, edad, estado, fechainicio, comentarios};
                model2.addRow(resalumno);
            }
            prepSt.close();
        } catch (NumberFormatException | SQLException e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_btnactualizaralumnosActionPerformed

    private void btncrearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncrearActionPerformed
        String horario = txthorario.getText();
        String dia = boxdia.getSelectedItem().toString();
        String num = numclase.getValue().toString();
        String tematica = txttematica.getText();
        
        String horavieja = "";
        
        String diaDB;
        if("Seleccione".equals(dia)){
            PopupMessage pum = new PopupMessage(0);
            pum.setVisible(true);
            return;
        }else{
            diaDB = clase.setDBValue(dia);
        }
        
        try{
            prepSt = conn.prepareStatement("SELECT * FROM `clasesemanal`");
            rs = prepSt.executeQuery();
            while(rs.next()){
                if(diaDB.equals(rs.getString("diasemana")) && horario.equals(rs.getString("hora"))){
                    PopupMessage pum = new PopupMessage(0);
                    pum.setVisible(true);
                    prepSt.close();
                    return;
                }
            }
            
            prepSt.close();
        }catch(SQLException e){
            e.printStackTrace();
            PopupMessage pum = new PopupMessage(0);
            pum.setVisible(true);
            return;
        }
        
        String statement = "INSERT INTO `clasesemanal` VALUES ('";
        if(horario == null || "Seleccione".equals(dia) || "0".equals(num)){
            PopupMessage pum = new PopupMessage(0);
            pum.setVisible(true);
        }else{
            statement += num + "', '" + diaDB + "', '" + horario + "', '0', '" + tematica + "')";
            try{
                prepSt = conn.prepareStatement(statement);
                prepSt.execute();
                prepSt.close();
                PopupMessage pum = new PopupMessage(4);
                pum.setVisible(true);
            }catch(SQLException e){
                e.printStackTrace();
                PopupMessage pum = new PopupMessage(0);
                pum.setVisible(true);
                return;
            }
            txthorario.setText("");
            boxdia.setSelectedIndex(0);
            numclase.setValue(0);
            txttematica.setText("");
            
            int numnum = Integer.parseInt(num);
            try{
                while(tablasemanal.getValueAt((numnum-1), Integer.parseInt(diaDB)) != null){
                    try{
                        String selectstatement = "SELECT * FROM `clasesemanal` WHERE `diasemana` = '" + diaDB + "' AND `id` = '" + numnum + "'";
                        System.out.println(selectstatement);
                        prepSt = conn.prepareStatement(selectstatement);
                        rs = prepSt.executeQuery();
                        while(rs.next()){
                            horavieja = rs.getString("hora");
                        }
                        prepSt.close();
                    }catch(SQLException e){
                            e.printStackTrace();
                    }
                    System.out.println("Checking cell...");
                    System.out.println("    Row: " + numnum);
                    System.out.println("    Column: " + diaDB);
                    if(tablasemanal.getValueAt(numnum-1, Integer.parseInt(diaDB)) != null){
                        System.out.println("NOT NULL");
                        String stselect = "SELECT * FROM `clasesemanal` WHERE `id` = '" + numnum + "' AND `diasemana` = '" + diaDB + "'";
                        System.out.println(stselect);

                        try {
                            String id = "";
                            String diasemana = "";
                            String hora = "";

                            prepSt = conn.prepareStatement(stselect);
                            rs = prepSt.executeQuery();
                            while(rs.next()){
                                id = rs.getString("id");
                                diasemana = rs.getString("diasemana");
                            }
                            int newid = Integer.parseInt(id)+1;

                            String stupdate = "UPDATE `clasesemanal` SET `ID` = '" + newid + "' WHERE `clasesemanal`.`diasemana` = " + diasemana + " AND `clasesemanal`.`hora` = '" + horavieja + "'";
                            System.out.println(stupdate);
                            prepSt = conn.prepareStatement(stupdate);
                            prepSt.execute();
                            prepSt.close();

                        } catch (SQLException e) {
                            e.printStackTrace();
                        }

                    }else{
                        System.out.println("NULL");
                    }
                    numnum++;
                }
            }catch(IndexOutOfBoundsException e){
                System.out.println(e.getMessage());
            }
        }
        
    }//GEN-LAST:event_btncrearActionPerformed

    private void btnactualizarclasesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnactualizarclasesActionPerformed
        int elitotal = tablasemanal.getRowCount();
        for(int i = elitotal-1; i>=0; i--){
            model3.removeRow(i);
        }
        String statement = "SELECT * FROM `clasesemanal`";
        System.out.println(statement);
        String[] empty = new String[0];
        try {
            prepSt = conn.prepareStatement(statement);
            rs = prepSt.executeQuery();
            while(rs.next()){
                String id = rs.getString("ID");
                int idint = Integer.parseInt(id);
                String diasemana = rs.getString("diasemana");
                int diasemanaint = Integer.parseInt(diasemana);
                String hora = rs.getString("hora");
                String numeroalumnos = rs.getString("numeroalumnos");
                
                int cantidadfilas = tablasemanal.getRowCount();
                cantidadfilas--;
                idint--;
                
                if(cantidadfilas > idint+1){
                    model3.setValueAt(hora + " - Ver Alumnos(" + numeroalumnos + ")", idint, diasemanaint);
                }else{
                    for(int i = idint - cantidadfilas; i > 0; i--){
                        model3.addRow(empty);
                    }
                    model3.setValueAt(hora + " - Ver Alumnos(" + numeroalumnos + ")", idint, diasemanaint);
                }
            }
        } catch (SQLException e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_btnactualizarclasesActionPerformed

    private void btnactualizarregistroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnactualizarregistroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnactualizarregistroActionPerformed

    private void tablasemanalMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablasemanalMouseClicked
        if(null != tablasemanal.getValueAt(tablasemanal.getSelectedRow(), tablasemanal.getSelectedColumn())){
            String doselementos[] = tablasemanal.getValueAt(tablasemanal.getSelectedRow(), tablasemanal.getSelectedColumn()).toString().split(" - ");
            String statement = "SELECT * FROM `clasesemanal` WHERE `hora` = '" + doselementos[0] + "' AND `diasemana` = " + tablasemanal.getSelectedColumn();
            System.out.println(statement);
            String[] infoclase = new String[5];
            try {
                prepSt = conn.prepareStatement(statement);
                rs = prepSt.executeQuery();
                for(int i = 0; rs.next(); i++){
                    infoclase[0] = rs.getString("ID");
                    infoclase[1] = rs.getString("diasemana");
                    infoclase[2] = rs.getString("hora");
                    infoclase[3] = rs.getString("numeroalumnos");
                    infoclase[4] = rs.getString("tematica");
                }
                prepSt.close();

                ViewerClaseSemanal VCS = new ViewerClaseSemanal();
                VCS.setClase(infoclase);
                VCS.setAlumnos();
//                VCS.setAnotaciones();
                VCS.setVCS(VCS);
                VCS.setTabla(tablasemanal);
                VCS.setVisible(true);
            } catch (SQLException e) {
                e.printStackTrace();
            }
        }
    }//GEN-LAST:event_tablasemanalMouseClicked

    private void btnresetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnresetActionPerformed
        String statement = "TRUNCATE TABLE `alumnos`";
        try{
            prepSt = conn.prepareStatement(statement);
            prepSt.execute();
        }catch(SQLException e){
            e.printStackTrace();
        }
    }//GEN-LAST:event_btnresetActionPerformed

    private void btnagregaralumno1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnagregaralumno1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnagregaralumno1ActionPerformed

    private void initModelConsultaAlumno(){
        model1.addColumn("Nombre");
        model1.addColumn("DNI");
        model1.addColumn("Telefono");
        model1.addColumn("Mail");
        model1.addColumn("Edad");
        model1.addColumn("Estado");
    }
    private void initModelListaAlumno(){
        model2.addColumn("Nombre");
        model2.addColumn("DNI");
        model2.addColumn("Telefono");
        model2.addColumn("Mail");
        model2.addColumn("Edad");
        model2.addColumn("Estado");
        model2.addColumn("Fecha inicio");
        model2.addColumn("Observaciones");
    }
    private void initModelListaSemanal(){
        model3.addColumn("Lunes");
        model3.addColumn("Martes");
        model3.addColumn("Miercoles");
        model3.addColumn("Jueves");
        model3.addColumn("Viernes");
        model3.addColumn("Sabado");
        tablasemanal.setRowHeight(50);
    }
    private void initModelRegistroClases(){
        model4.addColumn("ID");
        model4.addColumn("Fecha");
        model4.addColumn("Dia de la Semana");
        model4.addColumn("Hora");
        model4.addColumn("Alumnos");
        model4.addColumn("Observaciones");
    }
    
    @SuppressWarnings("Convert2Lambda")
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new MainFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> boxclase;
    private javax.swing.JComboBox<String> boxdia;
    private javax.swing.JComboBox<String> boxestado;
    private javax.swing.JComboBox<String> boxoperador;
    private javax.swing.JButton btnactualizaralumnos;
    private javax.swing.JButton btnactualizarclases;
    private javax.swing.JButton btnactualizarregistro;
    private javax.swing.JButton btnagregaralumno;
    private javax.swing.JButton btnagregaralumno1;
    private javax.swing.JButton btnbuscar;
    private javax.swing.JButton btncrear;
    private javax.swing.JButton btnlimpiar;
    private javax.swing.JButton btnreset;
    private javax.swing.JButton btntest;
    private javax.swing.JButton btnveralumnos;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable jTable4;
    private javax.swing.JSpinner numclase;
    private javax.swing.JSpinner numedad;
    private javax.swing.JSpinner numnewedad;
    private javax.swing.JTable tablaalumnos;
    private javax.swing.JTable tabladeresultados;
    private javax.swing.JTable tablaregistro;
    private javax.swing.JTable tablasemanal;
    private javax.swing.JTextArea txtanotaciones;
    private javax.swing.JTextField txtdni;
    private javax.swing.JTextField txtfecha;
    private javax.swing.JTextField txtfechainicio;
    private javax.swing.JTextField txthorario;
    private javax.swing.JTextField txtid;
    private javax.swing.JTextField txtmail;
    private javax.swing.JTextField txtnewalumno;
    private javax.swing.JTextField txtnewdni;
    private javax.swing.JTextField txtnewmail;
    private javax.swing.JTextField txtnewtelefono;
    private javax.swing.JTextField txtnombre;
    private javax.swing.JTextField txttelefono;
    private javax.swing.JTextPane txttematica;
    // End of variables declaration//GEN-END:variables
}
