/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package main;

import tools.PopupMessage;
import tools.Clase;
import tools.DBConnection;
import editors.EditorAlumno;
import editors.EditorAusencia;
import java.awt.Color;
import java.time.LocalDate;
import java.util.ArrayList;
import java.util.List;
import javax.swing.table.DefaultTableModel;
import tools.Alumno;

/**
 *
 * @author Edu
 */
public class AlumnoFrame extends javax.swing.JFrame {
    DefaultTableModel model1 = new DefaultTableModel();
    DefaultTableModel model2 = new DefaultTableModel();
    DefaultTableModel model3 = new DefaultTableModel();
    DefaultTableModel model4 = new DefaultTableModel();

    /**
     * Creates new form MainFrame
     */
    public AlumnoFrame() {
        initComponents();
        initModelConsultaAlumno();
        initModelListaAlumno();
        initModelListaAusencias();
        initModelListaPendientes();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel4 = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTable4 = new javax.swing.JTable();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tablaalumnos = new javax.swing.JTable();
        btnactualizaralumnos = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtnombre = new javax.swing.JTextField();
        txtdni = new javax.swing.JTextField();
        txttelefono = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtmail = new javax.swing.JTextField();
        btnbuscar = new javax.swing.JButton();
        jScrollPane5 = new javax.swing.JScrollPane();
        tabladeresultados = new javax.swing.JTable();
        jLabel7 = new javax.swing.JLabel();
        numedad = new javax.swing.JSpinner();
        boxestado = new javax.swing.JComboBox<>();
        boxoperador = new javax.swing.JComboBox<>();
        jPanel5 = new javax.swing.JPanel();
        txtalumno = new javax.swing.JTextField();
        txtnewdni = new javax.swing.JTextField();
        txtnewtelefono = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        txtfechainicio = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        btnagregaralumno = new javax.swing.JButton();
        txtnewmail = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        jScrollPane6 = new javax.swing.JScrollPane();
        txtanotaciones = new javax.swing.JTextArea();
        jLabel19 = new javax.swing.JLabel();
        txtnewnacimiento = new javax.swing.JTextField();
        jPanel7 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaausencias = new javax.swing.JTable();
        btnactualizarausencias = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();
        btnactualizarpendientes = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        tablapendientes = new javax.swing.JTable();

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 711, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 456, Short.MAX_VALUE)
        );

        jTable4.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane4.setViewportView(jTable4);

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        tablaalumnos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nombre", "DNI", "Mail", "Telefono", "Edad", "Fecha inicio", "Estado"
            }
        ));
        tablaalumnos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablaalumnosMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tablaalumnos);

        btnactualizaralumnos.setText("Actualizar");
        btnactualizaralumnos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnactualizaralumnosActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 969, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnactualizaralumnos, javax.swing.GroupLayout.PREFERRED_SIZE, 302, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jScrollPane2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnactualizaralumnos, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jTabbedPane1.addTab("Lista de Alumnos", jPanel3);

        jLabel1.setText("Nombre");

        txtnombre.setToolTipText("");
        txtnombre.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));

        jLabel3.setText("DNI");

        jLabel4.setText("Mail");

        jLabel5.setText("Teléfono");

        jLabel6.setText("Estado");

        jLabel2.setText("Edad");

        btnbuscar.setText("Buscar");
        btnbuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnbuscarActionPerformed(evt);
            }
        });

        tabladeresultados.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null}
            },
            new String [] {
                "Nombre", "DNI", "Telefono", "Mail", "Edad", "Estado"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        tabladeresultados.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        tabladeresultados.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabladeresultadosMouseClicked(evt);
            }
        });
        jScrollPane5.setViewportView(tabladeresultados);

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel7.setText("Resultados");

        numedad.setModel(new javax.swing.SpinnerNumberModel(0, null, 99, 1));

        boxestado.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione", "Activo", "Inactivo" }));

        boxoperador.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Igual a", "Mayor a", "Menor a" }));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane5)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(boxestado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(txtnombre)
                                .addComponent(txtdni)
                                .addComponent(txttelefono, javax.swing.GroupLayout.DEFAULT_SIZE, 261, Short.MAX_VALUE))
                            .addComponent(txtmail, javax.swing.GroupLayout.PREFERRED_SIZE, 261, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(boxoperador, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(28, 28, 28)
                                .addComponent(numedad, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 573, Short.MAX_VALUE))))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(211, 211, 211)
                .addComponent(btnbuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 236, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtnombre, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtdni, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txttelefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(boxoperador, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(numedad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(boxestado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane5, javax.swing.GroupLayout.DEFAULT_SIZE, 209, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(btnbuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Consulta Alumno", jPanel1);

        txtalumno.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));

        jLabel12.setText("DNI");

        jLabel15.setText("Nombre");

        txtfechainicio.setToolTipText("aaaa/mm/dd");

        jLabel16.setText("Mail");

        jLabel17.setText("Fecha de inicio");

        jLabel18.setText("Teléfono");

        btnagregaralumno.setText("Agregar");
        btnagregaralumno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnagregaralumnoActionPerformed(evt);
            }
        });

        jLabel20.setText("Anotaciones");

        txtanotaciones.setColumns(20);
        txtanotaciones.setRows(5);
        jScrollPane6.setViewportView(txtanotaciones);

        jLabel19.setText("Fecha de nacimiento");

        txtnewnacimiento.setToolTipText("aaaa/mm/dd");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel17, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel19, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtnewnacimiento, javax.swing.GroupLayout.PREFERRED_SIZE, 261, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jScrollPane6, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(txtfechainicio, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 261, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(txtalumno)
                        .addComponent(txtnewdni)
                        .addComponent(txtnewtelefono, javax.swing.GroupLayout.PREFERRED_SIZE, 261, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(txtnewmail, javax.swing.GroupLayout.PREFERRED_SIZE, 261, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 125, Short.MAX_VALUE)
                .addComponent(btnagregaralumno, javax.swing.GroupLayout.PREFERRED_SIZE, 348, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(90, 90, 90))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtalumno, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtnewdni, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtnewtelefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtnewmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtnewnacimiento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtfechainicio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane6, javax.swing.GroupLayout.DEFAULT_SIZE, 261, Short.MAX_VALUE)
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(35, 231, Short.MAX_VALUE))))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnagregaralumno, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        jTabbedPane1.addTab("Crear Alumno", jPanel5);

        tablaausencias.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Alumno", "Fecha", "ID en registro", "Razón", "Estado", "Recuperación"
            }
        ));
        tablaausencias.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablaausenciasMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tablaausencias);

        btnactualizarausencias.setText("Actualizar");
        btnactualizarausencias.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnactualizarausenciasActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 969, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnactualizarausencias, javax.swing.GroupLayout.PREFERRED_SIZE, 302, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 477, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnactualizarausencias, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jTabbedPane1.addTab("Registro ausencias", jPanel7);

        btnactualizarpendientes.setText("Actualizar");
        btnactualizarpendientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnactualizarpendientesActionPerformed(evt);
            }
        });

        tablapendientes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Alumno", "Fecha", "ID en registro", "Razón", "Estado", "Recuperación"
            }
        ));
        tablapendientes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablapendientesMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(tablapendientes);

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 969, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnactualizarpendientes, javax.swing.GroupLayout.PREFERRED_SIZE, 302, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 477, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnactualizarpendientes, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jTabbedPane1.addTab("Pendientes a recuperar", jPanel6);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(jTabbedPane1))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnagregaralumnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnagregaralumnoActionPerformed
        String DNI = txtnewdni.getText();
        String nombre = txtalumno.getText().toUpperCase();
        String mail = txtnewmail.getText().toUpperCase();
        String telefono = txtnewtelefono.getText();
        String nacimiento = txtnewnacimiento.getText();
        String inicio = txtfechainicio.getText();
        String anotaciones = txtanotaciones.getText();
        
        String statement = "INSERT INTO `alumnos` VALUES ('" + DNI + "', '" + nombre + "', ";
        if(!mail.equals("")){
            statement += "'" + mail + "', ";
        }else{
            statement += "null, ";
        }
        if(!telefono.equals("")){
            statement += "'" + telefono + "', ";
        }else{
            statement += "null, ";
        }
        if(!nacimiento.equals("")){
            statement += "'" + nacimiento + "', ";
        }else{
            statement += "null, ";
        }
        statement += "'" + inicio + "', '1')";
        
        if(DBConnection.getInstance().modificationStatement(statement)){
            if(!anotaciones.trim().equals("")){
                String anostatement = "INSERT INTO `comentariosalumnos` VALUES ('" + txtnewdni.getText() + "', '" + txtanotaciones.getText() + "')";
                DBConnection.getInstance().modificationStatement(anostatement);
            }else{
                String anostatement = "INSERT INTO `comentariosalumnos` VALUES ('" + txtnewdni.getText() + "', null)";
                DBConnection.getInstance().modificationStatement(anostatement);
            }
            
            txtalumno.setText("");
            txtnewnacimiento.setText("");
            txtnewtelefono.setText("");
            txtnewmail.setText("");
            txtnewdni.setText("");
            txtfechainicio.setText("");
            txtanotaciones.setText("");

            new PopupMessage("Alumno agregado con exito", Color.GREEN).setVisible(true);
        }else{
            new PopupMessage("Error", Color.RED).setVisible(true);
        }
    }//GEN-LAST:event_btnagregaralumnoActionPerformed

    private void tabladeresultadosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabladeresultadosMouseClicked
        String dni = (String)tabladeresultados.getValueAt(tabladeresultados.getSelectedRow(), 1);
        
        String statement = "SELECT * FROM `alumnos` WHERE dni = " + dni;
        List<String[]> infoAlumno = DBConnection.getInstance().selectStatement(statement, 7);
        if(Integer.parseInt(infoAlumno.get(0)[6]) == 0){
            infoAlumno.get(0)[6] = "Inactivo";
        }else{
            infoAlumno.get(0)[6] = "Activo";
        }
        
        String stselect = "SELECT * FROM `clasesemanal`";
        List<String[]> listClases = DBConnection.getInstance().selectStatement(stselect, 6);
        for(int i = 0; i < listClases.size(); i++){
            listClases.get(i)[2] = Clase.setClassValue(listClases.get(i)[2]);
        }
        
        EditorAlumno EA = new EditorAlumno();
        EA.setInfo(infoAlumno.get(0));
        EA.setClasesAlumno();
        EA.setOpcionesClases(listClases);
        EA.setAnotaciones();
        EA.setVisible(true);

    }//GEN-LAST:event_tabladeresultadosMouseClicked

    private void btnbuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnbuscarActionPerformed
        int elitotal = tabladeresultados.getRowCount();
        for(int i = elitotal-1; i>=0; i--){
            model1.removeRow(i);
        }
        
        boolean isFirst = false;
        String nombre = txtnombre.getText();
        String DNI = txtdni.getText();
        String telefono = txttelefono.getText();
        String mail = txtmail.getText();
        String edad = numedad.getValue().toString();
        String estado = boxestado.getSelectedItem().toString();
        
        //Check if any parameter is settled
        String statement = "SELECT * FROM `alumnos` ";
        if(!nombre.equals("") ||
            !DNI.equals("") ||
            !telefono.equals("") ||
            !mail.equals("") ||
            !edad.equals("0") ||
            !estado.equals("Seleccione")){

            statement = statement + "WHERE ";
            if(!nombre.equals("")){
                statement = statement + "`nombre` LIKE '" + nombre + "%' ";
                isFirst = true;
            }
            if(!DNI.equals("")){
                if(isFirst == true){
                    statement += "AND ";
                }
                statement = statement + "`DNI` LIKE '" + DNI + "%' ";
                isFirst = true;
            }
            if(!telefono.equals("")){
                if(isFirst == true){
                    statement += "AND ";
                }
                statement = statement + "`Telefono` LIKE '" + telefono + "%' ";
                isFirst = true;
            }
            if(!mail.equals("")){
                if(isFirst == true){
                    statement += "AND ";
                }
                statement = statement + "`Mail` LIKE '" + mail + "%' ";
                isFirst = true;
            }
            if(!edad.equals("0")){
                LocalDate currentDate = LocalDate.now();
                LocalDate maxDate = currentDate.minusYears(Long.parseLong(edad));
                LocalDate minDate = currentDate.minusYears(Long.parseLong(edad)+1).plusDays(1);
                
                if(isFirst == true){
                    statement += "AND ";
                }
                if(boxoperador.getSelectedItem().equals("Igual a")){
                    statement += "`FechaNacimiento` BETWEEN '" + minDate + "' AND '" + maxDate + "' ";
                }else if(boxoperador.getSelectedItem().equals("Mayor a")){
                    statement += "`FechaNacimiento` < '" + maxDate + "' ";
                }else{
                    statement += "`FechaNacimiento` > '" + maxDate + "' ";
                }
                isFirst = true;
            }
            if(!estado.equals("Seleccione")){
                if(isFirst == true){
                    statement += "AND ";
                }
                if(estado.equals("Activo")){
                    statement = statement + "`Estado` = 1 ";
                }else{
                    statement = statement + "`Estado` = 0 ";
                }
            }
        }
        List<String[]> list = DBConnection.getInstance().selectStatement(statement, 7);
        for(int i = 0; i < list.size(); i++){
            String[] str = list.get(i);
            String[] swapped1 = swap(str[0], str[1]);
            str[0] = swapped1[0];
            str[1] = swapped1[1];
            String[] swapped2 = swap(str[2], str[3]);
            str[2] = swapped2[0];
            str[3] = swapped2[1];
            String[] swapped3 = swap(str[5], str[6]);
            str[5] = swapped3[0];
            str[6] = swapped3[1];

            if(str[5].equals("1")){
                str[5] = "Activo";
            }else{
                str[5] = "Inactivo";
            }
            str[6] = null;

            Integer age = Alumno.getAge(str[4]);
            str[4] = age.toString();
            
            model1.addRow(str);
        }
    }//GEN-LAST:event_btnbuscarActionPerformed

    private void btnactualizaralumnosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnactualizaralumnosActionPerformed
        int elitotal = tablaalumnos.getRowCount();
        for(int i = elitotal-1; i>=0; i--){
            model2.removeRow(i);
        }
        String statement = "SELECT * FROM `alumnos`";
        List<String[]> list = DBConnection.getInstance().selectStatement(statement, 7);
        for(int i = 0; i < list.size(); i++){
            String[] str = list.get(i);
            String[] swapped = swap(str[0], str[1]);
            str[0] = swapped[0];
            str[1] = swapped[1];
            
            if(Integer.parseInt(list.get(i)[6]) == 0){
                list.get(i)[6] = "Inactivo";
            }else{
                list.get(i)[6] = "Activo";
            }
            Integer edad = Alumno.getAge(list.get(i)[4]);
            list.get(i)[4] = edad.toString();
            
            model2.addRow(list.get(i));
        }
    }//GEN-LAST:event_btnactualizaralumnosActionPerformed

    private void btnactualizarausenciasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnactualizarausenciasActionPerformed
        int elitotal = tablaausencias.getRowCount();
        for(int i = elitotal-1; i>=0; i--){
            model3.removeRow(i);
        }
        
        List<String> info = new ArrayList();
        String statement1 = "SELECT * FROM `ausencias`";
        List<String[]> listInfo = DBConnection.getInstance().selectStatement(statement1, 5);
        
        for(int i = 0; i < listInfo.size(); i++){
            info.clear();
            
            //Conseguir nombre del alumno
            String statement2 = "SELECT * FROM `alumnos` WHERE `DNI` = '" + listInfo.get(i)[1] + "'";
            List<String[]> nombreAlumno = DBConnection.getInstance().selectStatement(statement2, 7);
            info.add(nombreAlumno.get(0)[1]);
            
            //Conseguir fecha de la clase
            String statement3 = "SELECT * FROM `registroclases` WHERE `ID` = '" + listInfo.get(i)[0] + "'";
            List<String[]> fecha = DBConnection.getInstance().selectStatement(statement3, 3);
            info.add(fecha.get(0)[1]);
            
            //Agregar ID en registro
            info.add(listInfo.get(i)[0]);
            
            //Conseguir razon ausencia
            String statement4 = "SELECT * FROM `razonesausencias` WHERE `dni_alumno` = '" + listInfo.get(i)[1] + "' AND `id_registroclase` = '" + listInfo.get(i)[0] + "'";
            List<String[]> razon = DBConnection.getInstance().selectStatement(statement4, 3);
            info.add(razon.get(0)[2]);
            
            //Conseguir estado de la recuperación(pendiente a recuperar, no recupera, recuperada)
            if(listInfo.get(i)[4] == null){
                info.add("Pendiente");
            }else{
                switch (listInfo.get(i)[4]) {
                    case "0":
                        info.add("No recupera");
                        break;
                    case "1":
                        info.add("Recuperada");
                        break;
                }
            }
            
            //Conseguir clase a recuperar
            if(listInfo.get(i)[2] != null){
                String display = Clase.generateDisplayFromClassID(listInfo.get(i)[2]);
                if(listInfo.get(i)[3] != null){
                    display += " - " + listInfo.get(i)[3];
                }
                info.add(display);
            }else{
                info.add(null);
            }
            
            String[] str = {info.get(0), info.get(1), info.get(2), info.get(3), info.get(4), info.get(5)};
            model3.addRow(str);
        }
    }//GEN-LAST:event_btnactualizarausenciasActionPerformed

    private void btnactualizarpendientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnactualizarpendientesActionPerformed
        int elitotal = tablapendientes.getRowCount();
        for(int i = elitotal-1; i>=0; i--){
            model4.removeRow(i);
        }
        List<String> info = new ArrayList();
        String statement1 = "SELECT * FROM `ausencias` WHERE `recuperada` IS null";
        List<String[]> listInfo = DBConnection.getInstance().selectStatement(statement1, 5);
        
        if(listInfo.isEmpty()){
            return;
        }
        
        for(int i = 0; i < listInfo.size(); i++){
            info.clear();
            
            //Conseguir nombre del alumno
            String statement2 = "SELECT * FROM `alumnos` WHERE `DNI` = '" + listInfo.get(i)[1] + "'";
            List<String[]> nombreAlumno = DBConnection.getInstance().selectStatement(statement2, 7);
            info.add(nombreAlumno.get(0)[1]);
            
            //Conseguir fecha de la clase
            String statement3 = "SELECT * FROM `registroclases` WHERE `ID` = '" + listInfo.get(i)[0] + "'";
            List<String[]> fecha = DBConnection.getInstance().selectStatement(statement3, 3);
            info.add(fecha.get(0)[1]);
            
            //Agregar ID en registro
            info.add(listInfo.get(i)[0]);
            
            //Conseguir razon ausencia
            String statement4 = "SELECT * FROM `razonesausencias` WHERE `dni_alumno` = '" + listInfo.get(i)[1] + "' AND `id_registroclase` = '" + listInfo.get(i)[0] + "'";
            List<String[]> razon = DBConnection.getInstance().selectStatement(statement4, 3);
            info.add(razon.get(0)[2]);
            
            //Conseguir estado de la recuperación(pendiente a recuperar, no recupera, recuperada)
            if(listInfo.get(i)[4] == null){
                info.add("Pendiente");
            }else{
                switch (listInfo.get(i)[4]) {
                    case "0":
                        info.add("No recupera");
                        break;
                    case "1":
                        info.add("Recuperada");
                        break;
                }
            }
            
            //Conseguir clase a recuperar
            if(listInfo.get(i)[2] != null){
                info.add(Clase.generateDisplayFromClassID(listInfo.get(i)[2]));
            }else{
                info.add("");
            }
            
            String[] str = {info.get(0), info.get(1), info.get(2), info.get(3), info.get(4), info.get(5)};
            model4.addRow(str);
        }
    }//GEN-LAST:event_btnactualizarpendientesActionPerformed

    private void tablaalumnosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablaalumnosMouseClicked
        String dni = tablaalumnos.getValueAt(tablaalumnos.getSelectedRow(), 1).toString();
        
        String statement = "SELECT * FROM `alumnos` WHERE dni = " + dni;
        List<String[]> infoAlumno = DBConnection.getInstance().selectStatement(statement, 7);
        
        if(infoAlumno.isEmpty()){
            new PopupMessage("Error - actualizar tabla", Color.RED).setVisible(true);
            return;
        }
        
        if(Integer.parseInt(infoAlumno.get(0)[6]) == 0){
            infoAlumno.get(0)[6] = "Inactivo";
        }else{
            infoAlumno.get(0)[6] = "Activo";
        }
        
        String stselect = "SELECT * FROM `clasesemanal`";
        List<String[]> listClases = DBConnection.getInstance().selectStatement(stselect, 7);
        for(int i = 0; i < listClases.size(); i++){
            listClases.get(i)[2] = Clase.setClassValue(listClases.get(i)[2]);
        }
        
        EditorAlumno EA = new EditorAlumno();
        EA.setInfo(infoAlumno.get(0));
        EA.setClasesAlumno();
        EA.setOpcionesClases(listClases);
        EA.setAnotaciones();
        EA.setVisible(true);

    }//GEN-LAST:event_tablaalumnosMouseClicked

    private void tablapendientesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablapendientesMouseClicked
        List<String> info = new ArrayList();
        //Content: (Nombre, ID, Fecha, Estado, Fecha/clase de recuperación, razón)
        info.add(tablapendientes.getValueAt(tablapendientes.getSelectedRow(), 0).toString());
        info.add(tablapendientes.getValueAt(tablapendientes.getSelectedRow(), 2).toString());
        info.add(tablapendientes.getValueAt(tablapendientes.getSelectedRow(), 1).toString());
        info.add(tablapendientes.getValueAt(tablapendientes.getSelectedRow(), 4).toString());
        try{
            if(!tablapendientes.getValueAt(tablapendientes.getSelectedRow(), 5).toString().equals("")){
                info.add(tablapendientes.getValueAt(tablapendientes.getSelectedRow(), 5).toString());
            }else{
                info.add("");
            }
        }catch(Exception e){
            info.add("");
        }
        try{
            if(!tablapendientes.getValueAt(tablapendientes.getSelectedRow(), 3).toString().equals("")){
                info.add(tablapendientes.getValueAt(tablapendientes.getSelectedRow(), 3).toString());
            }else{
                info.add("");
            }
        }catch(Exception e){
            info.add("");
        }
        
        EditorAusencia EA = new EditorAusencia();
        EA.setInfo(info);
        EA.setVisible(true);
    }//GEN-LAST:event_tablapendientesMouseClicked

    private void tablaausenciasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablaausenciasMouseClicked
        List<String> info = new ArrayList();
        //Content: (0.Nombre, 1.ID, 2.Fecha, 3.Estado, 4.Fecha/clase de recuperación)
        info.add(tablaausencias.getValueAt(tablaausencias.getSelectedRow(), 0).toString());
        info.add(tablaausencias.getValueAt(tablaausencias.getSelectedRow(), 2).toString());
        info.add(tablaausencias.getValueAt(tablaausencias.getSelectedRow(), 1).toString());
        info.add(tablaausencias.getValueAt(tablaausencias.getSelectedRow(), 4).toString());
        try{
            if(!tablaausencias.getValueAt(tablaausencias.getSelectedRow(), 5).toString().equals("") || tablaausencias.getValueAt(tablaausencias.getSelectedRow(), 5) != null){
                info.add(tablaausencias.getValueAt(tablaausencias.getSelectedRow(), 5).toString());
            }else{
                info.add("");
            }
        }catch(Exception e){
            info.add("");
        }
        try{
            if(!tablaausencias.getValueAt(tablaausencias.getSelectedRow(), 3).toString().equals("")){
                info.add(tablaausencias.getValueAt(tablaausencias.getSelectedRow(), 3).toString());
            }else{
                info.add("");
            }
        }catch(Exception e){
            info.add("");
        }
            
        EditorAusencia EA = new EditorAusencia();
        EA.setInfo(info);
        EA.setVisible(true);
    }//GEN-LAST:event_tablaausenciasMouseClicked

    private String[] swap(String a, String b){
        String[] str = {b, a};
        return str;
    }
    
    private void initModelConsultaAlumno(){
        model1.addColumn("Nombre");
        model1.addColumn("DNI");
        model1.addColumn("Telefono");
        model1.addColumn("Mail");
        model1.addColumn("Edad");
        model1.addColumn("Estado");
        this.tabladeresultados.setModel(model1);
        tabladeresultados.setShowGrid(true);
    }
    private void initModelListaAlumno(){
        model2.addColumn("Nombre");
        model2.addColumn("DNI");
        model2.addColumn("Mail");
        model2.addColumn("Telefono");
        model2.addColumn("Edad");
        model2.addColumn("Fecha inicio");
        model2.addColumn("Estado");
        this.tablaalumnos.setModel(model2);
        tablaalumnos.setShowGrid(true);
    }
    private void initModelListaAusencias(){
        model3.addColumn("Alumno");
        model3.addColumn("Fecha");
        model3.addColumn("ID en registro");
        model3.addColumn("Razón");
        model3.addColumn("Estado");
        model3.addColumn("Recuperación");
        this.tablaausencias.setModel(model3);
        tablaausencias.setShowGrid(true);
    }
    private void initModelListaPendientes(){
        model4.addColumn("Alumno");
        model4.addColumn("Fecha");
        model4.addColumn("ID en registro");
        model4.addColumn("Razón");
        model4.addColumn("Estado");
        model4.addColumn("Recuperación");
        this.tablapendientes.setModel(model4);
        tablapendientes.setShowGrid(true);
    }
    
    @SuppressWarnings("Convert2Lambda")
    public static void main2(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AlumnoFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new AlumnoFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> boxestado;
    private javax.swing.JComboBox<String> boxoperador;
    private javax.swing.JButton btnactualizaralumnos;
    private javax.swing.JButton btnactualizarausencias;
    private javax.swing.JButton btnactualizarpendientes;
    private javax.swing.JButton btnagregaralumno;
    private javax.swing.JButton btnbuscar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable jTable4;
    private javax.swing.JSpinner numedad;
    private javax.swing.JTable tablaalumnos;
    private javax.swing.JTable tablaausencias;
    private javax.swing.JTable tabladeresultados;
    private javax.swing.JTable tablapendientes;
    private javax.swing.JTextField txtalumno;
    private javax.swing.JTextArea txtanotaciones;
    private javax.swing.JTextField txtdni;
    private javax.swing.JTextField txtfechainicio;
    private javax.swing.JTextField txtmail;
    private javax.swing.JTextField txtnewdni;
    private javax.swing.JTextField txtnewmail;
    private javax.swing.JTextField txtnewnacimiento;
    private javax.swing.JTextField txtnewtelefono;
    private javax.swing.JTextField txtnombre;
    private javax.swing.JTextField txttelefono;
    // End of variables declaration//GEN-END:variables
}