/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package main;

import tools.DBConnection;
import editors.EditorClaseSemanal;
import java.util.List;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import tools.Alumno;

/**
 *
 * @author Edu
 */
public class ViewerClaseSemanal extends javax.swing.JFrame {
    
    EditorClaseSemanal ECS;
    
    private String[] infoClase;
    DefaultTableModel model = new DefaultTableModel();
    private javax.swing.JTable tablasemanal;

    /**
     * Creates new form ViewerClaseSemanal
     */
    public ViewerClaseSemanal() {
        initComponents();
        initModel();
        
        txtanotaciones.setEditable(false);
        
    }
    
    public void setClase(String[] infoclase){
        this.infoClase = infoclase;
    }

    public void setAlumnos(){
        //Sets the list of Alumnos in the viewer
        String statement = "SELECT * FROM `clasesalumnos` WHERE `id_clase` = '" + infoClase[0] + "'";
        List<String[]> listDNI = DBConnection.getInstance().selectStatement(statement, 3);
        for(int i = 0; i < listDNI.size(); i++){
            String[] strDNI = listDNI.get(i);
            
            String selectst = "SELECT * FROM `alumnos` WHERE DNI = '" + strDNI[0] + "'";
            List<String[]> listNames = DBConnection.getInstance().selectStatement(selectst, 7);
            String[] strListAlu = listNames.get(0);
            String[] strName = {strListAlu[1]};
            
            if("1".equals(listDNI.get(i)[2])){
                strName[0] += " - RECUPERA";
            }
            
            model.addRow(strName);
        }
        this.tablaalumnos.setModel(model);
    }
    
    void setTabla(JTable tablasemanal) {
        this.tablasemanal = tablasemanal;
    }
    
    public void setAnotaciones(){
        String info = "";
        
        //Set class info
        if(infoClase[6] != null){
            info += "Temática de las clase: \n";
            info += infoClase[6] + "\n \n";
        }
        
        //Set alumno info
        String statement2 = "SELECT * FROM `clasesalumnos` WHERE `id_clase` = '" + infoClase[0] + "'";
        List<String[]> alumnos = DBConnection.getInstance().selectStatement(statement2, 2);
        for(int i = 0; i < alumnos.size(); i++){
            String statement3 = "SELECT * FROM `comentariosalumnos` WHERE `dni_alumno` = '" + alumnos.get(i)[0] + "'";
            List<String[]> patologias = DBConnection.getInstance().selectStatement(statement3, 2);
            if(patologias.get(0)[1] != null){
                info += Alumno.getNameFromDNI(alumnos.get(i)[0]) + ": " + patologias.get(0)[1] + "\n";
            }
        }
        
        txtanotaciones.setText(info);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaalumnos = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtanotaciones = new javax.swing.JTextPane();
        btneditar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setText("Anotaciones");

        tablaalumnos.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        tablaalumnos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Alumnos"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        tablaalumnos.setRowHeight(30);
        jScrollPane1.setViewportView(tablaalumnos);

        jScrollPane2.setViewportView(txtanotaciones);

        btneditar.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btneditar.setText("Editar clase");
        btneditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btneditarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 414, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 45, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btneditar, javax.swing.GroupLayout.PREFERRED_SIZE, 452, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 452, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btneditar, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 476, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(41, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btneditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btneditarActionPerformed
        ECS = new EditorClaseSemanal();
        ECS.setInfo(infoClase);
        ECS.setVCS(this);
        ECS.setTabla(tablasemanal);
        ECS.setVisible(true);
    }//GEN-LAST:event_btneditarActionPerformed

    /**
     * @param args the command line arguments
     */
    @SuppressWarnings("Convert2Lambda")
    public static void main2(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ViewerClaseSemanal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new ViewerClaseSemanal().setVisible(true);
            }
        });
    }
    
    private void initModel(){
        model.addColumn("Alumnos");
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btneditar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tablaalumnos;
    private javax.swing.JTextPane txtanotaciones;
    // End of variables declaration//GEN-END:variables

}
