/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package tools;

import java.time.LocalDate;
import java.util.List;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Edu
 */
public class PopupBirthweeks extends javax.swing.JFrame {
    
    DefaultTableModel model = new DefaultTableModel();
    
    /**
     * Creates new form PopupBirthweeks
     * @param infoCumples
     */
    public PopupBirthweeks(List<String[]> infoCumples) {
        initComponents();
        initModel();
        for(int i = 0; i < infoCumples.size(); i++){
            String[] yearMonthDay = infoCumples.get(i)[1].split("-");
            infoCumples.get(i)[1] = getMonth(yearMonthDay[1]) + " - " + yearMonthDay[2];
            model.addRow(infoCumples.get(i));
        }
    }
    
    private static String getMonth(String month){
        String monthValue = month;
        switch(month){
            case "01":
                monthValue = "Enero";
                break;
            case "02":
                monthValue = "Febrero";
                break;
            case "03":
                monthValue = "Marzo";
                break;
            case "04":
                monthValue = "Abril";
                break;
            case "05":
                monthValue = "Mayo";
                break;
            case "06":
                monthValue = "Junio";
                break;
            case "07":
                monthValue = "Julio";
                break;
            case "08":
                monthValue = "Agosto";
                break;
            case "09":
                monthValue = "Septiembre";
                break;
            case "10":
                monthValue = "Octubre";
                break;
            case "11":
                monthValue = "Noviembre";
                break;
            case "12":
                monthValue = "Diciembre";
                break;
        }
        return monthValue;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tablacumpleaños = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        tablacumpleaños.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        tablacumpleaños.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nombre", "Fecha"
            }
        ));
        jScrollPane1.setViewportView(tablacumpleaños);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setText("Cumpleaños de la semana");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 257, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 146, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 31, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 445, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    @SuppressWarnings("Convert2Lambda")
    public static void main2(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PopupBirthweeks.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
            //</editor-fold>
            
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
            }
        });
    }

    private void initModel(){
        model.addColumn("Nombre");
        model.addColumn("Fecha");
        tablacumpleaños.setModel(model);
        tablacumpleaños.setShowGrid(true);
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tablacumpleaños;
    // End of variables declaration//GEN-END:variables
}
